extends RefCounted
## 1-9 "The King's Road". The set -- ground, keep wall, backdrop, traps, cannon,
## gatehouse and castle -- is cut by tools/import_castle_art.py from the flat
## key-art set; the characters by tools/import_pv_assets.py from
## docs/art-prompts-characters.md.
const TEXTURES := {
	"castle_hound_0": "castle/castle_hound_0.png",
	"castle_hound_1": "castle/castle_hound_1.png",
	"castle_hound_2": "castle/castle_hound_2.png",
	"castle_hound_3": "castle/castle_hound_3.png",
	"castle_hound_4": "castle/castle_hound_4.png",
	"castle_hound_5": "castle/castle_hound_5.png",
	"castle_hound_6": "castle/castle_hound_6.png",
	"castle_hound_7": "castle/castle_hound_7.png",
	"castle_bat_0": "castle/castle_bat_0.png",
	"castle_bat_1": "castle/castle_bat_1.png",
	"castle_bat_2": "castle/castle_bat_2.png",
	"castle_bat_3": "castle/castle_bat_3.png",
	"castle_golem_0": "castle/castle_golem_0.png",
	"castle_golem_1": "castle/castle_golem_1.png",
	"castle_golem_2": "castle/castle_golem_2.png",
	"castle_golem_3": "castle/castle_golem_3.png",
	"castle_golem_4": "castle/castle_golem_4.png",
	"castle_golem_5": "castle/castle_golem_5.png",
	"castle_panorama": "castle/castle_panorama.jpg",
	"castle_ground_tile": "castle/castle_ground_tile.png",
	"castle_ground_cap": "castle/castle_ground_cap.png",
	"castle_bridge_end": "castle/castle_bridge_end.png",
	"castle_cannon_idle": "castle/castle_cannon_idle.png",
	"castle_cannon_fire": "castle/castle_cannon_fire.png",
	"castle_cannonball": "castle/castle_cannonball.png",
	"castle_boulder": "castle/castle_boulder.png",
	"castle_gate_arch": "castle/castle_gate_arch.png",
	"castle_gate_bars": "castle/castle_gate_bars.png",
	"castle_dungeon_wall": "castle/castle_dungeon_wall.png",
	"castle_torch": "castle/castle_torch.png",
	"castle_keep_wall": "castle/castle_keep_wall.png",
	"castle_goal_door": "castle/castle_goal_door.png",
	"castle_water": "castle/castle_water.png",
	"castle_brick": "castle/castle_brick.png",
	"castle_stone": "castle/castle_stone.png",
	"castle_bush_0": "castle/castle_bush_0.png",
	"castle_bush_1": "castle/castle_bush_1.png",
	"castle_spike_block": "castle/castle_spike_block.png",
	"castle_spike_ball": "castle/castle_spike_ball.png",
	"castle_chain": "castle/castle_chain.png",
}
